# Configuraci�n de la base de datos (para producci�n)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuraci�n del pool de conexiones (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# Propiedades para JWT
jwt.secreto=${JWT_SECRETO}
jwt.expiracion=3600000

# Propiedades para Swagger (opcional)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuraci�n de logging (para producci�n)
logging.level.org.springframework=INFO
logging.level.com.apitareas=INFO
logging.file.name=logs/apitareas.log

# Puerto para HTTPS (si usas Spring Boot con HTTPS)
server.port=8443